# Generated by Django 4.2.5 on 2023-10-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dualisuser',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
